[versions]
androidx-test = '1.7.0'
androidx-junit-ext = '1.3.0'
androidx-junit-ext-ktx = '1.3.0'
androidx-uiautomator = '2.3.0'
androidx-espresso = '3.7.0'
espresso-contrib = '3.0.2'

[libraries]
androidx-core = { group = 'androidx.test', name = 'core', version.ref = 'androidx-test' }
androidx-runner = { group = 'androidx.test', name = 'runner', version.ref = 'androidx-test' }
androidx-rules = { group = 'androidx.test', name = 'rules', version.ref = 'androidx-test' }
androidx-junit-ext = { group = 'androidx.test.ext', name = 'junit', version.ref = 'androidx-junit-ext' }
androidx-junit-ext-ktx = { group = 'androidx.test.ext', name = 'junit-ktx', version.ref = 'androidx-junit-ext-ktx' }
androidx-uiautomator = { group = 'androidx.test.uiautomator', name = 'uiautomator', version.ref = 'androidx-uiautomator' }
androidx-espresso-core = { group = 'androidx.test.espresso', name = 'espresso-core', version.ref = 'androidx-espresso' }
androidx-espresso-intents = { group = 'androidx.test.espresso', name = 'espresso-intents', version.ref = 'androidx-espresso' }
espresso-contrib = { group = 'com.android.support.test.espresso', name = 'espresso-contrib', version.ref = 'espresso-contrib' }
