[versions]
agp = '8.6.1'
kotlin = '1.9.22'
mavenPublish = '0.27.0'
dokka = '1.9.20'
detekt = '1.23.5'
kover = '0.8.3'
appcompat = '1.6.1'
core-ktx = '1.12.0'
material = '1.11.0'
okhttp = '4.12.0'
cardio = '5.5.1'
blinkcard = "2.9.3"
activity-compose = '1.8.2'
androidx-compose = '1.6.2'
constraintlayout = '2.1.4'
multidex = '2.0.1'
preference-ktx = '1.2.1'
codeview = '1.3.2'
fuel = '2.3.1'
espresso-idling-resource = '3.6.1'
wallet = '19.4.0'

[plugins]
android-application = { id = 'com.android.application', version.ref = 'agp' }
android-library = { id = 'com.android.library', version.ref = 'agp' }
kotlin-android = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin' }
kotlin-parcelize = { id = 'org.jetbrains.kotlin.plugin.parcelize', version.ref = 'kotlin' }
maven-publish = { id = 'com.vanniktech.maven.publish', version.ref = 'mavenPublish' }
dokka = { id = 'org.jetbrains.dokka', version.ref = 'dokka' }
detekt = { id = 'io.gitlab.arturbosch.detekt', version.ref = 'detekt' }
kover = { id = 'org.jetbrains.kotlinx.kover', version.ref = 'kover' }

[libraries]
androidx-appcompat = { group = 'androidx.appcompat', name = 'appcompat', version.ref = 'appcompat' }
androidx-core-ktx = { group = 'androidx.core', name = 'core-ktx', version.ref = 'core-ktx' }
androidx-constraintlayout = { group = 'androidx.constraintlayout', name = 'constraintlayout', version.ref = 'constraintlayout' }
material = { group = 'com.google.android.material', name = 'material', version.ref = 'material' }
okhttp = { group = 'com.squareup.okhttp3', name = 'okhttp', version.ref = 'okhttp' }
dokka-base = { group = 'org.jetbrains.dokka', name = 'dokka-base', version.ref = 'dokka' }
cardio = { group = 'io.card', name = 'android-sdk', version.ref = 'cardio' }
blinkcard = { group = 'com.microblink', name = 'blinkcard', version.ref = "blinkcard" }
activity-compose = { group = 'androidx.activity', name = 'activity-compose', version.ref = 'activity-compose' }
compose-material = { group = 'androidx.compose.material', name = 'material', version.ref = 'androidx-compose' }
compose-ui-tooling-preview = { group = 'androidx.compose.ui', name = 'ui-tooling-preview', version.ref = 'androidx-compose' }
androidx-multidex = { group = 'androidx.multidex', name = 'multidex', version.ref = 'multidex' }
androidx-preference-ktx = { group = 'androidx.preference', name = 'preference-ktx', version.ref = 'preference-ktx' }
codeview = { group = 'com.github.kbiakov', name = 'CodeView-Android', version.ref = 'codeview' }
fuel = { group = 'com.github.kittinunf.fuel', name = 'fuel', version.ref = 'fuel' }
espresso-idling-resource = { group = 'androidx.test.espresso', name = 'espresso-idling-resource', version.ref = 'espresso-idling-resource' }
play-services-wallet = { group = 'com.google.android.gms', name = 'play-services-wallet', version.ref = 'wallet' }
