[versions]
agp = "8.13.1"
kotlin = "2.2.21"
mokkery = "2.10.2"
mavenPublish = '0.35.0'
dokka = '2.1.0'
detekt = '1.23.8'
kover = '0.9.4'
appcompat = '1.7.1'
core-ktx = '1.17.0'
material = '1.13.0'
okhttp = '5.3.2'
cardio = '5.5.1'
blinkcard = "2.12.0"
activity-compose = '1.10.1'
androidx-compose = '1.9.5'
constraintlayout = '2.2.1'
multidex = '2.0.1'
preference-ktx = '1.2.1'
codeview = '1.3.2'
fuel = '2.3.1'
espresso-idling-resource = '3.7.0'
wallet = '19.4.0'
ktor = "3.3.2"
kotlin-coroutines-test = "1.10.2"
vgs-sdk-analytics-android = "1.0.3"

[plugins]
android-application = { id = 'com.android.application', version.ref = 'agp' }
android-library = { id = 'com.android.library', version.ref = 'agp' }
kotlin-android = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin' }
kotlin-parcelize = { id = 'org.jetbrains.kotlin.plugin.parcelize', version.ref = 'kotlin' }
maven-publish = { id = 'com.vanniktech.maven.publish', version.ref = 'mavenPublish' }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
dokka = { id = 'org.jetbrains.dokka', version.ref = 'dokka' }
detekt = { id = 'io.gitlab.arturbosch.detekt', version.ref = 'detekt' }
kover = { id = 'org.jetbrains.kotlinx.kover', version.ref = 'kover' }

[libraries]
androidx-appcompat = { group = 'androidx.appcompat', name = 'appcompat', version.ref = 'appcompat' }
androidx-core-ktx = { group = 'androidx.core', name = 'core-ktx', version.ref = 'core-ktx' }
androidx-constraintlayout = { group = 'androidx.constraintlayout', name = 'constraintlayout', version.ref = 'constraintlayout' }
material = { group = 'com.google.android.material', name = 'material', version.ref = 'material' }
okhttp = { group = 'com.squareup.okhttp3', name = 'okhttp', version.ref = 'okhttp' }
dokka-base = { group = 'org.jetbrains.dokka', name = 'dokka-base', version.ref = 'dokka' }
cardio = { group = 'io.card', name = 'android-sdk', version.ref = 'cardio' }
#noinspection Aligned16KB
blinkcard = { group = 'com.microblink', name = 'blinkcard', version.ref = "blinkcard" }
activity-compose = { group = 'androidx.activity', name = 'activity-compose', version.ref = 'activity-compose' }
compose-material = { group = 'androidx.compose.material', name = 'material', version.ref = 'androidx-compose' }
compose-ui-tooling-preview = { group = 'androidx.compose.ui', name = 'ui-tooling-preview', version.ref = 'androidx-compose' }
androidx-multidex = { group = 'androidx.multidex', name = 'multidex', version.ref = 'multidex' }
androidx-preference-ktx = { group = 'androidx.preference', name = 'preference-ktx', version.ref = 'preference-ktx' }
codeview = { group = 'com.github.kbiakov', name = 'CodeView-Android', version.ref = 'codeview' }
fuel = { group = 'com.github.kittinunf.fuel', name = 'fuel', version.ref = 'fuel' }
espresso-idling-resource = { group = 'androidx.test.espresso', name = 'espresso-idling-resource', version.ref = 'espresso-idling-resource' }
play-services-wallet = { group = 'com.google.android.gms', name = 'play-services-wallet', version.ref = 'wallet' }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines-test" }
vgs-sdk-analytics-android = { module = "com.verygoodsecurity:vgs-sdk-analytics-android", version.ref = "vgs-sdk-analytics-android" }
