---
name: 'CI'

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write  # For publishing test results

jobs:
  run-unit-tests:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup environment
        uses: ./.github/actions/setup
        env:
          VGS_VAULT_ID: ${{ secrets.VGS_VAULT_ID }}

      - name: Run Detekt
        run: ./gradlew vgscollect:detekt --continue

      - name: Run Unit Tests
        run: ./gradlew vgscollect:testDebugUnitTest --continue

      - name: (Compass) Generate Code Coverage Report
        id: coverage
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew vgscollect:koverHtmlReportDebug
          
          COVERAGE=$(sed -n '51p' vgscollect/build/reports/kover/htmlDebug/index.html)
          METRIC_VALUE=`echo ${COVERAGE//[[:space:]]/} | sed 's/.$//'`
          
          echo "metric_value=$METRIC_VALUE" >> $GITHUB_OUTPUT

      - name: (Compass) Publish code coverage
        if: github.ref == 'refs/heads/main'
        uses: verygood-ops/cicd-shared/.github/actions/compass@compass-action-v1.0.0
        with:
          metric_source_id: 'ari:cloud:compass:83673fa7-fd28-4f4a-9738-f584064570a7:component/db43f86d-85fe-42e1-954d-457f5a4082b8/dde6f82f-6e9f-4a9d-a79b-820223a44310'
          metric_value: ${{ steps.coverage.outputs.metric_value }}
          api_key: ${{ secrets.COMPASS_API_KEY }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: unit-test-results
          path: |
            **/build/test-results/**/*.xml
            **/build/reports/**
          retention-days: 30

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: ${{ !cancelled() }}
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          check_name: 'Unit Test Results'
          fail_on_failure: true

  run-ui-tests:
    name: 'Run UI Tests'
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'release/') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup environment
        uses: ./.github/actions/setup
        env:
          VGS_VAULT_ID: ${{ secrets.VGS_VAULT_ID }}

      - name: Auth Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Assemble debug & test APK
        run: ./gradlew  app:assembleDebug app:assembleAndroidTest

      - name: Run UI tests
        run: |
          gcloud firebase test android run \
          --type instrumentation \
          --app app/build/outputs/apk/debug/app-debug.apk \
          --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
          --device model=oriole,version=31,locale=en,orientation=portrait \
          --device model=blazer,version=36,locale=en,orientation=portrait