name: security-scan-sast

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '40 3 * * 5'

jobs:
  scan:
    if: false
    uses: verygood-ops/cicd-shared/.github/workflows/security-scan-sast.yaml@security-scan-sast-v2
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SAST_SLACK_WORKFLOW_WEBHOOK: ${{ secrets.SAST_SLACK_WORKFLOW_WEBHOOK }}
